# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b388e97cd93bc3d09e702de3404cf63"
name = "test-app-training"
handle = "test-app-training-1"
application_url = "https://connectivity-hayes-wales-handbook.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "developmentcheck.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://connectivity-hayes-wales-handbook.trycloudflare.com/auth/callback",
  "https://connectivity-hayes-wales-handbook.trycloudflare.com/auth/shopify/callback",
  "https://connectivity-hayes-wales-handbook.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
